// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskHub.Api.Data;

#nullable disable

namespace TaskHub.Api.Migrations
{
    [DbContext(typeof(TaskHubDbContext))]
    [Migration("20260210045231_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskHub.Api.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2891),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "ChongHsien Task Description",
                            DueDate = new DateTime(2026, 2, 17, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2885),
                            Priority = 0,
                            Status = 0,
                            Title = "ChongHsien Task",
                            UpdatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2891)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2895),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "YeeChian Task Description",
                            DueDate = new DateTime(2026, 2, 18, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2895),
                            Priority = 1,
                            Status = 1,
                            Title = "YeeChian Task",
                            UpdatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2896)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2899),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Falcon Task Description",
                            DueDate = new DateTime(2026, 2, 19, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2899),
                            Priority = 2,
                            Status = 2,
                            Title = "Falcon Task",
                            UpdatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2900)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2904),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "ChongHsien toFalcon Task Description",
                            DueDate = new DateTime(2026, 2, 20, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2903),
                            Priority = 0,
                            Status = 4,
                            Title = "ChongHsien to Falcon Task",
                            UpdatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2904)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2916),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "YeeChian Task Description",
                            DueDate = new DateTime(2026, 2, 21, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2915),
                            Priority = 2,
                            Status = 3,
                            Title = "YeeChian to Falcon Task",
                            UpdatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2916)
                        });
                });

            modelBuilder.Entity("TaskHub.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2769),
                            PasswordHash = "ChongHsien",
                            Role = 0,
                            UserName = "ChongHsien"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2773),
                            PasswordHash = "YeeChian",
                            Role = 1,
                            UserName = "YeeChian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 10, 4, 52, 30, 942, DateTimeKind.Utc).AddTicks(2783),
                            PasswordHash = "Falcon",
                            Role = 2,
                            UserName = "Falcon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
