// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskHub.Api.Data;

#nullable disable

namespace TaskHub.Api.Migrations
{
    [DbContext(typeof(TaskHubDbContext))]
    [Migration("20260219094758_AddUserActive")]
    partial class AddUserActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskHub.Api.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7482),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "ChongHsien Task Description",
                            DueDate = new DateTime(2026, 2, 26, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7478),
                            Priority = 0,
                            Status = 0,
                            Title = "ChongHsien Task",
                            UpdatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7482)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7486),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "YeeChian Task Description",
                            DueDate = new DateTime(2026, 2, 27, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7486),
                            Priority = 1,
                            Status = 1,
                            Title = "YeeChian Task",
                            UpdatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7487)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7521),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "Falcon Task Description",
                            DueDate = new DateTime(2026, 2, 28, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7521),
                            Priority = 2,
                            Status = 2,
                            Title = "Falcon Task",
                            UpdatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7522)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7529),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "ChongHsien toFalcon Task Description",
                            DueDate = new DateTime(2026, 3, 1, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7529),
                            Priority = 0,
                            Status = 4,
                            Title = "ChongHsien to Falcon Task",
                            UpdatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7530)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AssigneeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7533),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "YeeChian Task Description",
                            DueDate = new DateTime(2026, 3, 2, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7533),
                            Priority = 2,
                            Status = 3,
                            Title = "YeeChian to Falcon Task",
                            UpdatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7534)
                        });
                });

            modelBuilder.Entity("TaskHub.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Active = true,
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7384),
                            PasswordHash = "ChongHsien",
                            Role = 0,
                            UserName = "ChongHsien"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Active = true,
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7387),
                            PasswordHash = "YeeChian",
                            Role = 1,
                            UserName = "YeeChian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Active = true,
                            CreatedAt = new DateTime(2026, 2, 19, 9, 47, 58, 773, DateTimeKind.Utc).AddTicks(7388),
                            PasswordHash = "Falcon",
                            Role = 2,
                            UserName = "Falcon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
